project_name: ddbimport

before:
  hooks:
    - cd sls && make package

builds:
-
  env:
    - CGO_ENABLED=0
  dir: cmd
  main: main.go
  binary: ddbimport
  ldflags:
   - -s -w -X github.com/a-h/ddbimport/version.Version={{.Version}} -X github.com/a-h/ddbimport/version.Commit={{.Commit}}
  goos:
      - linux
      - windows
      - darwin

# Sign with GPG.
signs:
  - artifacts: checksum

archives:
- format: binary

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

# Add the Step Functions package seperately for deployment.
release:
  extra_files:
    - glob: ./sls/package.zip

